include /ioc/tools/driver.makefile
PROJECT = bestec
EXCLUDE_VERSIONS += 3
BUILDCLASSES += Linux

SOURCES += ../bestecApp/src/bestec.cpp
SOURCES += ../bestecApp/src/bestecPGM.cpp
DBDS += ../bestecApp/src/bestecSupport.dbd

QT += ../bestecApp/op/ui/bestecMono.ui
